### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [CoolMineman/quiltgoslightlyfasterlol#2]
Wondering if macOS is planned

**Comment by unilock** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/11802133/202322626-c6180854-3a5d-49b3-8638-53f0dcb286dc.png">

https://modrinth.com/mod/quiltgoslighlyfasterlol

**Comment by Aces-and-Jacks** [comment]
I know it says none. But it could probably change. Didn't give a clear descriptor saying "I don't plan on supporting these platforms"

**Comment by Aces-and-Jacks** [comment]
That's why I'm asking. If it'll be like that indefinitely or not

**Comment by unilock** [comment]
That's a list of [target triplets](https://wiki.osdev.org/Target_Triplet), not the support statuses of each platform.
Since the definition of a "triplet" is somewhat loose, it's a bit hard to explain what that really means.

Basically, macOS is supported.

***

Each supported platform is in the format `xxxx-yyyy-zzzz`.
- `xxxx` = architecture (aarch64 = [AArch64](https://en.wikipedia.org/wiki/AArch64) | x86 = [IA-32](https://en.wikipedia.org/wiki/IA-32) | powerpc64le = [ppc64](https://en.wikipedia.org/wiki/Ppc64) | x86_64 = [x86-64](https://en.wikipedia.org/wiki/X86-64))
- `yyyy` = operating system
- `zzzz` = [C standard library](https://en.wikipedia.org/wiki/C_standard_library#Implementations) implentation? (gnu = [glibc](https://en.wikipedia.org/wiki/Glibc); none = ???)

**Comment by Aces-and-Jacks** [comment]
ohhhh. My bad

**Comment by Aces-and-Jacks** [comment]
I didn't see anything about target triplets so I just assumed that none meant unsupported
